### ISSUE TITLE
Windows Control button

### ISSUE THREAD

**Issue by edwardally** [Zonnev/elementaryos-thunderbird-theme#1]
I understand that this feature is currently a work in progress. Is there any way to manually change it?

![image](https://github.com/Zonnev/elementaryos-thunderbird-theme/assets/1024003/74f3428c-26b8-4d33-9634-3c3169a93351)

**Comment by Zonnev** [comment]
You can now look for the **window button control layout**  you are using and put the `base.css` from the root and the `userChrome.css` from the **corresponding folder** _(the folder name tells the window button control layouts from Pantheon Tweaks)_ in your `chrome` folder.

Maybe in the future there will be an install script for this. Good luck!

**Comment by edwardally** [comment]
Thanks @Zonnev 

Non of those control layout are working after the latest update

![image](https://github.com/Zonnev/elementaryos-thunderbird-theme/assets/1024003/f34e16f5-e2d2-4f71-93f7-e079f4a65f81)


![image](https://github.com/Zonnev/elementaryos-thunderbird-theme/assets/1024003/0fc34913-ee80-46eb-8f77-454e5ec5b83e)

**Comment by edwardally** [comment]
Thank you @Zonnev 

The latest update are perfectly working fine now.
